ARG  base_image=r.studio73.es/odoo/community:11
FROM ${base_image} as builder
COPY --chown=odoo 11.0/openupgrade.yaml /code/openupgrade.yaml
RUN cd /code && gitaggregate --config openupgrade.yaml

FROM ${base_image}
COPY --chown=odoo --from=builder /code/openupgrade $SRC/odoo/odoo
ENV OPENUPGRADE_TARGET_VERSION=11.0
