ARG BASE_TAG=12
FROM r.studio73.es/odoo/base:${BASE_TAG}
RUN mkdir -p $SRC/studio73
COPY --chown=odoo 12.0/community.yaml $SRC/studio73
RUN --mount=type=ssh,uid=1000 cd $SRC/studio73 && gitaggregate --jobs 8 --config community.yaml
RUN sed -i 's/git+https:\/\/github\.com\/OCA\/openupgradelib\.git/openupgradelib/g' $SRC/studio73/studio73-private-addons/requirements.txt
RUN install-requirements $SRC/studio73
