ARG BASE_TAG=12
FROM r.studio73.es/odoo/community:${BASE_TAG}
RUN mkdir -p $SRC/studio73
RUN --mount=type=ssh,uid=1000 cd $SRC/studio73 && gitaggregate --jobs 8 -c repos.yaml -d zenterprise/*
RUN install-requirements $SRC/studio73
