---
platform: linux

image_resource:
  type: registry-image
  source:
    repository: concourse/oci-build-task
inputs:
  - name: repo
outputs:
  - name: image
run:
  path: /bin/sh
  args:
    - -c
    - |
      export CONTEXT=repo
      export DOCKERFILE=repo/$ODOO_VERSION/Dockerfile
      export BUILD_ARG_BUILD_DATE=$(date -u +"%Y-%m-%dT%H:%M:%SZ")
      echo $ODOO_VERSION.$(date -u +"%Y%m%d") > image/today-tag
      build
