---
platform: linux

image_resource:
  type: registry-image
  source:
    username: ((REGISTRY_USER))
    password: ((REGISTRY_SECRET))
    repository: r.studio73.es/odoo/oci-build
    tag: latest
inputs:
  - name: repo
  - name: base-image
outputs:
  - name: image
run:
  path: /bin/sh
  args:
    - -c
    - |
      export CONTEXT=repo/odoo
      export DOCKERFILE=repo/odoo/$ODOO_VERSION.0/Dockerfile.$VERSION
      build-tag
caches:
  - path: cache
