---
platform: linux

image_resource:
  type: registry-image
  source:
    username: ((REGISTRY_USER))
    password: ((REGISTRY_SECRET))
    repository: r.studio73.es/odoo/tools
    tag: latest
inputs:
  - name: repo
outputs:
  - name: repo
run:
  path: tools
  args:
    - update-repos
    - --cwd=repo
    - --config=$ODOO_VERSION/$VERSION.yaml
    - --add-open-prs
