---
platform: linux

image_resource:
  type: registry-image
  source:
    repository: r.studio73.es/odoo/tools
    tag: latest
inputs:
  - name: repo-odoo
outputs:
  - name: repo-odoo
run:
  path: /bin/bash
  args:
    - -c
    - |
      set -e
      VERSIONS="14.0 15.0"
      ORGS="odoo oca"
      cd repo-odoo/odoo
      for VERSION in $VERSIONS; do
        for VERSION in $VERSIONS; do
          tools repos update --version=$VERSION --config=$VERSION/$ORG.yaml --commit
        done
      done

