---
meta:
  x-notify: &notify-handlers
    on_success:
      put: notify
      inputs: [pr]
      params: {state: success}
    on_failure:
      put: notify
      inputs: [pr]
      params: {state: failure}
    on_error:
      put: notify
      inputs: [pr]
      params: {state: error}
    on_abort:
      put: notify
      inputs: [pr]
      params: {state: error}

resource_types:
  - name: pull-request
    type: docker-image
    check_every: 24h
    source:
      repository: teliaoss/github-pr-resource
  - name: cogito
    type: registry-image
    check_every: 24h
    source:
      repository: pix4d/cogito

resources:
  - name: repo
    type: git
    icon: github
    check_every: 24h
    webhook_token: ((WEBHOOK_TOKEN))
    source:
      uri: https://github.com/Studio73/dodoo.git
      branch: master
      username: ((GITHUB_TOKEN))
      password: x-oauth-basic
  - name: sunday
    type: time
    icon: clock-outline
    source:
      days: [Sunday]
      start: 04:00
      stop: 05:00
      location: Europe/Madrid
      initial_version: true
  - name: base-14
    type: registry-image
    icon: docker
    source:
      username: ((REGISTRY_USER))
      password: ((REGISTRY_SECRET))
      repository: r.studio73.es/odoo/base
      tag: 14
  - name: base-15
    type: registry-image
    icon: docker
    source:
      username: ((REGISTRY_USER))
      password: ((REGISTRY_SECRET))
      repository: r.studio73.es/odoo/base
      tag: 15
  - name: pr
    type: pull-request
    icon: github
    check_every: 24h
    webhook_token: ((WEBHOOK_TOKEN))
    source:
      repository: Studio73/dodoo
      access_token: ((GITHUB_TOKEN))
  - name: notify
    type: cogito
    icon: bell-ring
    check_every: 24h
    source:
      owner: Studio73
      repo: dodoo
      access_token: ((GITHUB_TOKEN))
      gchat_webhook: ((GCHAT_CONCOURSE_WEBHOOK))

groups:
  - name: master
    jobs:
      - set-self
      - update-repos
      - build-base-14
      - build-base-15
  - name: pr
    jobs:
      - build-base-14-pr
      - build-base-15-pr
  - name: all
    jobs:
      - "*"


jobs:
  - name: set-self
    plan:
      - get: repo
        trigger: true
      - set_pipeline: self
        file: repo/.ci/pipeline.yaml
  - name: update-repos
    plan:
      - get: sunday
        trigger: true
      - get: repo
      - task: update
        attempts: 3
        params:
          GITHUB_TOKEN: ((GITHUB_TOKEN))
        file: repo/.ci/tasks/update-repos.yaml
      - put: repo
        params: {repository: repo}
  - name: build-base-14
    plan:
      - get: repo
        trigger: true
        passed: [set-self]
      - task: build-image
        attempts: 3
        privileged: true
        params:
          ODOO_VERSION: "14"
        file: repo/.ci/tasks/build.yaml
        output_mapping: {image: "base-14"}
      - put: base-14
        params: 
          image: base-14/image.tar
          additional_tags: base-14/today-tag
  - name: build-base-15
    plan:
      - get: repo
        trigger: true
        passed: [set-self]
      - task: build-image
        attempts: 3
        privileged: true
        params:
          ODOO_VERSION: "15"
        file: repo/.ci/tasks/build.yaml
        output_mapping: {image: "base-15"}
      - put: base-15
        params: 
          image: base-15/image.tar
          additional_tags: base-15/today-tag
  - name: build-base-14-pr
    <<: *notify-handlers
    plan:
      - get: pr
        trigger: true
      - put: notify
        inputs: [pr]
        params: {state: pending}
      - task: build-image
        attempts: 3
        privileged: true
        input_mapping: {repo: pr}
        params:
          ODOO_VERSION: "14"
        file: pr/.ci/tasks/build.yaml
  - name: build-base-15-pr
    <<: *notify-handlers
    plan:
      - get: pr
        trigger: true
      - put: notify
        inputs: [pr]
        params: {state: pending}
      - task: build-image
        attempts: 3
        privileged: true
        input_mapping: {repo: pr}
        params:
          ODOO_VERSION: "15"
        file: pr/.ci/tasks/build.yaml
