---
meta:
  x-notify: &notify
    on_failure:
      put: notify
      inputs: [repo]
      params: {state: failure}
    on_error:
      put: notify
      inputs: [repo]
      params: {state: error}
  x-notify-pr: &notify-pr
    on_success:
      put: notify
      inputs: [pr]
      params: {state: success}
    on_failure:
      put: notify
      inputs: [pr]
      params: {state: failure}
    on_error:
      put: notify
      inputs: [pr]
      params: {state: error}
    on_abort:
      put: notify
      inputs: [pr]
      params: {state: error}

resource_types:
  - name: pull-request
    type: docker-image
    check_every: 24h
    source:
      repository: teliaoss/github-pr-resource
  - name: cogito
    type: registry-image
    check_every: 24h
    source:
      repository: pix4d/cogito

resources:
  - name: sunday
    type: time
    icon: clock-outline
    source:
      days: [Sunday]
      start: 04:00
      stop: 05:00
      location: Europe/Madrid
      initial_version: true
  - name: repo
    type: git
    icon: github
    check_every: 24h
    webhook_token: ((WEBHOOK_TOKEN))
    source:
      uri: https://github.com/Studio73/dodoo.git
      branch: master
      username: ((GITHUB_TOKEN))
      password: x-oauth-basic
  - name: repo-odoo
    type: git
    icon: folder-sync
    check_every: 24h
    webhook_token: ((WEBHOOK_TOKEN))
    source:
      uri: https://github.com/Studio73/dodoo.git
      branch: master
      username: ((GITHUB_TOKEN))
      password: x-oauth-basic
      paths:
        - odoo/*
  - name: repo-proxypass
    type: git
    icon: folder-sync
    check_every: 24h
    webhook_token: ((WEBHOOK_TOKEN))
    source:
      uri: https://github.com/Studio73/dodoo.git
      branch: master
      username: ((GITHUB_TOKEN))
      password: x-oauth-basic
      paths:
        - proxypass/*
  - name: repo-oci
    type: git
    icon: folder-sync
    check_every: 24h
    webhook_token: ((WEBHOOK_TOKEN))
    source:
      uri: https://github.com/Studio73/dodoo.git
      branch: master
      username: ((GITHUB_TOKEN))
      password: x-oauth-basic
      paths:
        - oci-build/*
  - name: repo-tools
    type: git
    icon: folder-sync
    check_every: 24h
    webhook_token: ((WEBHOOK_TOKEN))
    source:
      uri: https://github.com/Studio73/dodoo.git
      branch: master
      username: ((GITHUB_TOKEN))
      password: x-oauth-basic
      paths:
        - tools/*
  - name: pr
    type: pull-request
    icon: github
    check_every: 24h
    webhook_token: ((WEBHOOK_TOKEN))
    source:
      repository: Studio73/dodoo
      access_token: ((GITHUB_TOKEN))
      paths:
        - odoo/*
  - name: oci-build
    type: registry-image
    icon: docker
    check_every: 24h
    source:
      username: ((REGISTRY_USER))
      password: ((REGISTRY_SECRET))
      repository: r.studio73.es/odoo/oci-build
      tag: latest
  - name: oci-build-task
    type: registry-image
    icon: docker
    check_every: 24h
    source:
      repository: concourse/oci-build-task
      tag: latest
  - name: proxypass
    type: registry-image
    icon: docker
    check_every: 24h
    source:
      username: ((REGISTRY_USER))
      password: ((REGISTRY_SECRET))
      repository: r.studio73.es/odoo/proxypass
      tag: latest
  - name: tools
    type: registry-image
    icon: docker
    check_every: 24h
    source:
      username: ((REGISTRY_USER))
      password: ((REGISTRY_SECRET))
      repository: r.studio73.es/odoo/tools
      tag: latest
  - name: base-14
    type: registry-image
    icon: docker
    check_every: 24h
    source:
      username: ((REGISTRY_USER))
      password: ((REGISTRY_SECRET))
      repository: r.studio73.es/odoo/base
      tag: 14
  - name: base-15
    type: registry-image
    icon: docker
    check_every: 24h
    source:
      username: ((REGISTRY_USER))
      password: ((REGISTRY_SECRET))
      repository: r.studio73.es/odoo/base
      tag: 15
  - name: notify
    type: cogito
    icon: bell-ring
    check_every: 24h
    source:
      owner: Studio73
      repo: dodoo
      access_token: ((GITHUB_TOKEN))
      gchat_webhook: ((GCHAT_CONCOURSE_WEBHOOK))

groups:
  - name: all
    jobs:
      - "*"
  - name: master
    jobs:
      - update-repos
      - build-oci
      - build-proxypass
      - build-tools
      - build-base-14
      - build-base-15
  - name: pr
    jobs:
      - build-base-14-pr
      - build-base-15-pr

jobs:
  - name: update-repos
    <<: *notify
    plan:
      - get: sunday
        trigger: true
      - get: repo
      - task: update
        attempts: 3
        params:
          GITHUB_TOKEN: ((GITHUB_TOKEN))
        file: repo/.ci/tasks/update-repos.yaml
      - put: repo
        params: {repository: repo}
  - name: build-oci
    <<: *notify
    plan:
      - in_parallel:
          - get: repo
          - get: repo-oci
            trigger: true
          - get: oci-build-task
            trigger: true
      - task: build-image
        attempts: 3
        privileged: true
        params:
          CONTEXT: repo/oci-build
        file: repo/.ci/tasks/build.yaml
        output_mapping: {image: oci-build}
      - put: oci-build
        params:
          image: oci-build/image.tar
  - name: build-proxypass
    <<: *notify
    plan:
      - in_parallel:
          - get: repo
          - get: repo-proxypass
            trigger: true
      - task: build-image
        attempts: 3
        privileged: true
        params:
          CONTEXT: repo/proxypass
        file: repo/.ci/tasks/build.yaml
        output_mapping: {image: "proxypass"}
      - put: proxypass
        params:
          image: proxypass/image.tar
  - name: build-tools
    <<: *notify
    plan:
      - in_parallel:
          - get: repo
          - get: repo-tools
            trigger: true
      - task: build-image
        attempts: 3
        privileged: true
        params:
          CONTEXT: repo/tools
        file: repo/.ci/tasks/build.yaml
        output_mapping: {image: "tools"}
      - put: tools
        params:
          image: tools/image.tar
  - name: build-base-14
    <<: *notify
    plan:
      - in_parallel:
          - get: repo
          - get: repo-odoo
            trigger: true
      - task: build-image
        attempts: 3
        privileged: true
        params:
          ODOO_VERSION: "14"
        file: repo/.ci/tasks/build-base.yaml
        output_mapping: {image: "base-14"}
      - put: base-14
        params:
          image: base-14/image.tar
          additional_tags: base-14/today-tag
  - name: build-base-15
    <<: *notify
    plan:
      - in_parallel:
          - get: repo
          - get: repo-odoo
            trigger: true
      - task: build-image
        attempts: 3
        privileged: true
        params:
          ODOO_VERSION: "15"
        file: repo/.ci/tasks/build-base.yaml
        output_mapping: {image: "base-15"}
      - put: base-15
        params:
          image: base-15/image.tar
          additional_tags: base-15/today-tag
  - name: build-base-14-pr
    <<: *notify-pr
    plan:
      - get: pr
        trigger: true
      - put: notify
        inputs: [pr]
        params: {state: pending}
      - task: build-image
        attempts: 3
        privileged: true
        input_mapping: {repo: pr}
        params:
          ODOO_VERSION: "14"
        file: pr/.ci/tasks/build-base.yaml
  - name: build-base-15-pr
    <<: *notify-pr
    plan:
      - get: pr
        trigger: true
      - put: notify
        inputs: [pr]
        params: {state: pending}
      - task: build-image
        attempts: 3
        privileged: true
        input_mapping: {repo: pr}
        params:
          ODOO_VERSION: "15"
        file: pr/.ci/tasks/build-base.yaml
