name: "Merge PRs"
description: "Merge PRs"
inputs:
  merges:
    description: "List of PRs numbers to merge"
    required: true
  ssh_key:
    description: "SSH Private Key"
    required: true
runs:
  using: "docker"
  image: "docker://r.studio73.es/actions/merge-prs:latest"
