ARG BASE_TAG=15
FROM r.studio73.es/odoo/community:${BASE_TAG}
COPY --chown=odoo 15.0/openupgrade.yaml $SRC/oca
RUN --mount=type=ssh,uid=1000 cd $SRC/oca && gitaggregate --jobs 8 --config openupgrade.yaml
ENV OPENUPGRADE_TARGET_VERSION=15.0
