ARG BASE_VERSION=15
FROM r.studio73.es/odoo/community:${BASE_VERSION}
RUN --mount=type=ssh,uid=1000 cd $SRC/studio73 && gitaggregate --jobs 8 -c repos.yaml -d zenterprise/*
RUN install-requirements $SRC/studio73
