ARG  base_image=r.studio73.es/odoo/community:10
FROM ${base_image} as builder
ARG SSH_KEY
RUN set-ssh-key
COPY --chown=odoo 10.0/enterprise.yaml /code/enterprise.yaml
RUN cd /code && gitaggregate --jobs 8 --config enterprise.yaml aggregate

FROM ${base_image}
COPY --chown=odoo --from=builder /code $SRC/studio73
RUN install-requirements $SRC/studio73
