ARG BASE_TAG=13
FROM r.studio73.es/odoo/community:${BASE_TAG} AS builder
COPY --chown=odoo 13.0/openupgrade.yaml /code/openupgrade.yaml
RUN --mount=type=ssh,uid=1000 cd /code && gitaggregate --config openupgrade.yaml

FROM r.studio73.es/odoo/community:${BASE_TAG}
COPY --chown=odoo --from=builder /code/openupgrade $SRC/odoo/odoo
ENV OPENUPGRADE_TARGET_VERSION=13.0
