ARG BASE_TAG=9
FROM r.studio73.es/odoo/base:${BASE_TAG}
RUN mkdir -p $SRC/studio73
COPY --chown=odoo 9.0/community.yaml $SRC/studio73
RUN --mount=type=ssh,uid=1000 cd $SRC/studio73 && gitaggregate --jobs 8 --config community.yaml
RUN install-requirements $SRC/studio73
