---
platform: linux

image_resource:
  type: registry-image
  source:
    username: ((REGISTRY_USER))
    password: ((REGISTRY_SECRET))
    repository: r.studio73.es/odoo/oci-build
    tag: latest
inputs:
  - name: repo
  - name: odoo
outputs:
  - name: image
run:
  path: build-tag
caches:
  - path: cache
