---
platform: linux

image_resource:
  type: registry-image
  source:
    username: ((REGISTRY_USER))
    password: ((REGISTRY_SECRET))
    repository: r.studio73.es/odoo/tools
inputs:
  - name: pr
run:
  path: /bin/bash
  args:
    - -c
    - |
      export PRE_COMMIT_HOME=$(pwd)/cache
      tools lint -c $(pwd)/pr
caches:
  - path: cache
