---
platform: linux

image_resource:
  type: registry-image
  source:
    username: ((REGISTRY_USER))
    password: ((REGISTRY_SECRET))
    repository: r.studio73.es/odoo/tools
inputs:
  - name: repo
outputs:
  - name: repo
run:
  path: tools
  args:
    - update-repos
    - --cwd=repo
