name: Build
on:
  push:
    branches:
      master

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version: ["10.0", "11.0", "12.0", "13.0", "14.0"]
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 2
      - name: Set pyversion
        id: pyversion
        run: |
          if [ ${{ matrix.version }} == 10.0 ]; then
            echo ::set-output name=version::py2;
          elif [ ${{ matrix.version }} == 11.0 ] || [ ${{ matrix.version }} == 12.0 ]; then
            echo ::set-output name=version::py3.6;
          else
            echo ::set-output name=version::py3.8;
          fi
      - name: Git log
        id: log
        run: echo "::set-output name=message::$(git log --no-merges -1 --oneline)"
      - name: Build and push ${{ matrix.version }}
        if: "!contains(steps.log.outputs.message, 'skip build')"
        uses: docker/build-push-action@v1
        with:
          repository: dodoo
          registry: registry.studio73.es
          username: ${{ secrets.DOCKER_S73_USERNAME }}
          password: ${{ secrets.DOCKER_S73_PASSWORD }}
          dockerfile: ${{ steps.pyversion.outputs.version }}/Dockerfile
          tags: ${{ matrix.version }}
          build_args: VERSION=${{ matrix.version }}
          add_git_labels: true

