name: Concourse Webhook (Master)
on:
  push:
    branches:
      - master
jobs:
  trigger-resource-check:
    runs-on: ubuntu-20.04
    steps:
      - name: Trigger repo
        uses: gstackio/trigger-concourse-resource-check-action@v1
        with:
          concourse-url: https://ci.studio73.dev
          concourse-team: odoo
          concourse-pipeline: dodoo
          concourse-resource: repo
          concourse-webhook-token: ${{ secrets.CONCOURSE_WEBHOOK_TOKEN }}
      - name: Trigger repo/oci-build
        uses: gstackio/trigger-concourse-resource-check-action@v1
        with:
          concourse-url: https://ci.studio73.dev
          concourse-team: odoo
          concourse-pipeline: dodoo
          concourse-resource: repo-oci-build
          concourse-webhook-token: ${{ secrets.CONCOURSE_WEBHOOK_TOKEN }}
      - name: Trigger repo/proxypass
        uses: gstackio/trigger-concourse-resource-check-action@v1
        with:
          concourse-url: https://ci.studio73.dev
          concourse-team: odoo
          concourse-pipeline: dodoo
          concourse-resource: repo-proxypass
          concourse-webhook-token: ${{ secrets.CONCOURSE_WEBHOOK_TOKEN }}
      - name: Trigger repo/tools
        uses: gstackio/trigger-concourse-resource-check-action@v1
        with:
          concourse-url: https://ci.studio73.dev
          concourse-team: odoo
          concourse-pipeline: dodoo
          concourse-resource: repo-tools
          concourse-webhook-token: ${{ secrets.CONCOURSE_WEBHOOK_TOKEN }}
      - name: Trigger repo/odoo-14
        uses: gstackio/trigger-concourse-resource-check-action@v1
        with:
          concourse-url: https://ci.studio73.dev
          concourse-team: odoo
          concourse-pipeline: dodoo
          concourse-resource: repo-odoo-14
          concourse-webhook-token: ${{ secrets.CONCOURSE_WEBHOOK_TOKEN }}
      - name: Trigger repo/odoo-15
        uses: gstackio/trigger-concourse-resource-check-action@v1
        with:
          concourse-url: https://ci.studio73.dev
          concourse-team: odoo
          concourse-pipeline: dodoo
          concourse-resource: repo-odoo-15
          concourse-webhook-token: ${{ secrets.CONCOURSE_WEBHOOK_TOKEN }}
