name: Odoo PR

on:
  pull_request:
    branches: ["master"]
    paths:
      - "odoo/**"
    types: [ready_for_review, opened, synchronize, reopened]
jobs:
  generate-matrix:
    name: Generate job matrices
    runs-on: self-hosted
    outputs:
      versions: ${{ steps.version.outputs.matrix }}
    steps:
      - name: Generate matrix | versions
        id: version
        uses: hellofresh/action-changed-files@v3
        with:
          pattern: odoo/(?P<version>[\d]+)
          defaults: true # Run all combinations
  build:
    runs-on: self-hosted
    needs: [generate-matrix]
    strategy:
      fail-fast: false
      matrix:
        ${{ fromJson(inputs.odoo_version || needs.generate-matrix.outputs.versions) }}
    if: ${{ fromJson(inputs.odoo_version ||
      needs.generate-matrix.outputs.versions).include[0] }} # skip if the matrix is empty!
    steps:
      - uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
      - uses: actions/checkout@v4
      - name: Setup buildx
        uses: docker/setup-buildx-action@v2
      - name: Base
        uses: ./actions/odoo-build
        with:
          image: r.studio73.es/odoo/base
          file: odoo/${{ matrix.version }}.0/Dockerfile.base
          build_date: $(date -u '+%y-%m-%d-%H%M%S')
          tag: ${{ matrix.version }}
          push: false
